## 1. 

In [15]:
%autosave 5

Autosaving every 5 seconds


In [2]:
list1=[1,1,1.1,"Harshith",True, None]
print(list1)

[1, 1, 1.1, 'Harshith', True, None]


## 2. 

In [3]:
lists = [1, 2, 3, 4, 5]

element = 3

if element in lists:
    print(f"{element} is in the list.")
else:
    print(f"{element} is not in the list.")

3 is in the list.


## 3. 

In [4]:
lengths = len(lists)
print(lengths)

5


## 4. 

In [5]:
square_list = []

for i in range(1,6):
    square_list.append(i**2)
print(square_list)
    

[1, 4, 9, 16, 25]


## 5. 

In [6]:
arr = [1, 2, 3, 4, 5]
rev = arr[::-1]
print("Reversed array:", rev)

Reversed array: [5, 4, 3, 2, 1]


## 6. 

In [7]:
arr = [3, 2, 3, 4, 5]

arr.sort(reverse=True)
print("Sorted array:", arr)

Sorted array: [5, 4, 3, 3, 2]


## 7. 

In [8]:
list1 = [1, 2, 3, 4]
list2 = [5, 3, 2, 1]

list1.sort()
list2.sort()
if list1 ==list2:
    print("Same Same")
else:
    print("Different")

if set(list1) == set(list2):
    print("Same")
else:
    print("not same.")


Different
not same.


## 8. 

In [9]:
result = cmp(list1,list2)  #won't work
if result<0:
    print("list 1 is less")
elif result == 0:
    print("Equal")
elif result>0:
    print("list 2 is less")

NameError: name 'cmp' is not defined

## 9. 

In [10]:
cars = ["Ford", "Volvo", "BMW","Maruti","TATA","Hyundai"]
cars.remove("Ford")
print(cars)
cars.pop()
print(cars)
cars.pop(0)
print(cars)
cars.clear()
print(cars)

['Volvo', 'BMW', 'Maruti', 'TATA', 'Hyundai']
['Volvo', 'BMW', 'Maruti', 'TATA']
['BMW', 'Maruti', 'TATA']
[]


## 10. 

In [11]:
import numpy as np

integer_array = np.array([1, 2, 3, 4, 5], dtype=int)

float_array = np.asfarray(integer_array)

print("Original integer array:")
print(integer_array)
print("Converted floating-point array:")
print(float_array)
print("Data type of the converted array:")
print(float_array.dtype)


Original integer array:
[1 2 3 4 5]
Converted floating-point array:
[1. 2. 3. 4. 5.]
Data type of the converted array:
float64


## 11. 

In [12]:
import numpy as np

list1 = [1, 2, 3, 4, 5]
tuple1= (6, 7, 8, 9, 10)

array_list = np.array(list1)
array_tuple = np.array(tuple1)

print("Original list:")
print(list1)
print("Converted array from list:")
print(array_from_list)

print("\nOriginal tuple:")
print(tuple1)
print("Converted array from tuple:")
print(array_from_tuple)


Original list:
[1, 2, 3, 4, 5]
Converted array from list:


NameError: name 'array_from_list' is not defined

## 12. 

In [14]:
import numpy as np

list1 = [1, 2, 3, 4, 5]
tuple1= (6, 7, 8, 9, 10)

array_list = np.asarray(list1)
array_tuple = np.asarray(tuple1)

print("Original list:")
print(list1)
print("Converted array from list:")
print(array_list)

print("\nOriginal tuple:")
print(tuple1)
print("Converted array from tuple:")
print(array_tuple)

Original list:
[1, 2, 3, 4, 5]
Converted array from list:
[1 2 3 4 5]

Original tuple:
(6, 7, 8, 9, 10)
Converted array from tuple:
[ 6  7  8  9 10]
